export const FONTS = [
  { id: 'serif', name: 'Serif', class: 'font-serif' },
  { id: 'sans', name: 'Sans', class: 'font-sans' },
  { id: 'mono', name: 'Mono', class: 'font-mono' },
  { id: 'inter', name: 'Inter', class: 'font-[Inter]', import: 'Inter:wght@400;500;600;700' },
  { id: 'poppins', name: 'Poppins', class: 'font-[Poppins]', import: 'Poppins:wght@400;500;600;700' },
  { id: 'playfair', name: 'Playfair', class: 'font-[Playfair_Display]', import: 'Playfair+Display:wght@400;500;600;700' },
  { id: 'lora', name: 'Lora', class: 'font-[Lora]', import: 'Lora:wght@400;500;600;700' },
  { id: 'roboto', name: 'Roboto', class: 'font-[Roboto]', import: 'Roboto:wght@400;500;700' },
  { id: 'opensans', name: 'Open Sans', class: 'font-[Open_Sans]', import: 'Open+Sans:wght@400;500;600;700' },
  { id: 'montserrat', name: 'Montserrat', class: 'font-[Montserrat]', import: 'Montserrat:wght@400;500;600;700' },
  { id: 'raleway', name: 'Raleway', class: 'font-[Raleway]', import: 'Raleway:wght@400;500;600;700' },
  { id: 'merriweather', name: 'Merriweather', class: 'font-[Merriweather]', import: 'Merriweather:wght@400;700' },
  { id: 'nunito', name: 'Nunito', class: 'font-[Nunito]', import: 'Nunito:wght@400;500;600;700' },
  { id: 'dm-sans', name: 'DM Sans', class: 'font-[DM_Sans]', import: 'DM+Sans:wght@400;500;600;700' },
  { id: 'dm-serif', name: 'DM Serif', class: 'font-[DM_Serif_Display]', import: 'DM+Serif+Display' },
  { id: 'space-grotesk', name: 'Space Grotesk', class: 'font-[Space_Grotesk]', import: 'Space+Grotesk:wght@400;500;600;700' },
  { id: 'outfit', name: 'Outfit', class: 'font-[Outfit]', import: 'Outfit:wght@400;500;600;700' },
  { id: 'sora', name: 'Sora', class: 'font-[Sora]', import: 'Sora:wght@400;500;600;700' },
  { id: 'crimson', name: 'Crimson Text', class: 'font-[Crimson_Text]', import: 'Crimson+Text:wght@400;600;700' },
  { id: 'jetbrains', name: 'JetBrains Mono', class: 'font-[JetBrains_Mono]', import: 'JetBrains+Mono:wght@400;500;600;700' },
  { id: 'source-serif', name: 'Source Serif', class: 'font-[Source_Serif_4]', import: 'Source+Serif+4:wght@400;600;700' },
];
